name: "🛡️ GTM Security Audit Request"
description: "Request a high-level psychological and technical audit of a GTM target."
title: "[AUDIT]: <Company Name>"
labels: ["audit", "high-priority"]
body:
  - type: markdown
    attributes:
      value: |
        ### 🦅 NEXUS::AUDIT PROTOCOL
        This request initiates a deep refinery audit of the target entity.
  - type: input
    id: target
    attributes:
      label: Target Company
      placeholder: e.g. Amazon Web Services
    validations:
      required: true
  - type: textarea
    id: signals
    attributes:
      label: Known Signals
      placeholder: Paste recent news, hiring links, or LinkedIn noise...
  - type: dropdown
    id: intensity
    attributes:
      label: Audit Intensity
      options:
        - Layer 01 (Substrate Only)
        - Layer 13 (Audit + Intent)
        - Layer 22 (Full Superposition)
    validations:
      required: true
